### ISSUE TITLE
Function as nodeRepulsion option

### ISSUE THREAD

**Issue by mikpom** [cytoscape/cytoscape.js-cose-bilkent#71] opened 2018-02-27 22:41 UTC
I was wondering if I could use arbitrary function as layout option `nodeRepulsion` argument?
Cose layout in the core allows that but I am getting an error if when using the same function for cose-bilkent.

Thanks,
Mikhail

**Comment by maxkfranz** [comment] 2018-02-28 14:51
This is a good idea, but I would argue that it's generally more useful to set functions for the edge options, like the edge length.  Anyway, all element-related options should allow functions for per-element values -- like regular COSE -- not just node charge.

**Comment by DukeBaird** [comment] 2018-05-17 20:04
A function for node repulsion or edge length would be quite helpful for me. I tried a quick modification but it seems to be more complicated that I had thought.

**Comment by bradh** [comment] 2018-07-07 06:02
I just added a PR for edge length if you want to try it out - see #74

**Comment by ugurdogrusoz** [comment] 2020-11-19 12:39
This is a duplicate of https://github.com/cytoscape/cytoscape.js-cose-bilkent/issues/1.

**Closed by ugurdogrusoz** 2020-11-19 12:39 UTC
